-- AlterTable
ALTER TABLE "public"."settings" ADD COLUMN     "maxFScore" DOUBLE PRECISION DEFAULT 100,
ADD COLUMN     "maxScore" DOUBLE PRECISION DEFAULT 100,
ADD COLUMN     "minFScore" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "minScore" DOUBLE PRECISION DEFAULT 0;
