services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - CI=1
      - FORCE_COLOR=0
      - NO_COLOR=1
      - TERM=xterm
    networks:
      - ls
  db:
    image: postgres:16.3
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql@16/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--no-locale"
    networks:
      - ls
    ports:
      - '5432:5432'
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - ls

volumes:
  postgres-data:

networks:
  ls:
